apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: naveen19/base64-express:1.0.0
        ports:
        - containerPort: 8080
