apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      name: react-app
      labels:
        app: react-app
    spec:
      containers:
      - name: reacte-app
        image: naveen19/react-app:1.0.0
        ports:
        - containerPort: 3000
